spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/batch
      username: root
      password: pass
      driver-class-name: com.mysql.cj.jdbc.Driver

---

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: e207.woojoobook@gmail.com
    password: hpsp mtuu udnz znun
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

---
